---

- name: Install necessary packages for Docker
  apt:
    name: 
      - ca-certificates
      - curl
    state: latest
    update_cache: yes

# - name: Install keyrings
# #   shell: install -m 0755 -d /etc/apt/keyrings

- name: Download GPG key
  get_url:
    url: http://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    force_basic_auth: yes
    mode: 0444

- name: Add docker repos to apt sources
  shell: |
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null


- name: Install Docker
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes


