---
- name: Install Chrony
  import_tasks: chrony.yml
  tags: chrony

- name: Install Docker
  import_tasks: docker_install.yml
  tags: docker_install

- name: set PiHole
  import_tasks: pihole.yml
  tags: pihole
